<div class="page-title">
    <h1><?php echo $this->__('My Gift Cards') ?></h1>
</div>
<form name="giftcardForm" action="<?php echo $this->getUrl('customer/giftcards/balance') ?>" method="post">
    <table border="0" cellpadding="1" cellspacing="1">
        <tr>
            <td><?php echo $this->__('Check Gift Card Balance') ?>:</td>

        </tr>
        <tr>
            <td><?php echo $this->__('Enter the Gift Card code') ?>:</td>
            <td><input class="input-text" id="giftcard_code" name="giftcard_code" value=""/></td>
        </tr>
        <?php if(($aResult = $this->getCurrentBalance()) !== false): ?>
            <tr>
                <td>&nbsp;</td>
                <td><?php echo 'Gift Card: "'.$aResult['card_code'].'" '.Mage::helper('core')->currency($aResult['card_balance']); ?></td>
            </tr>
        <?php endif;?>
        <tr>
            <td colspan="2" align="center">
                <button type="button" title="<?php echo $this->__('Check') ?>" class="button"
                        onclick="document.forms['giftcardForm'].submit()" value="<?php echo $this->__('Redeem') ?>">
                    <span><span><?php echo $this->__('Check') ?></span></span></button>
            </td>
        </tr>
    </table>
</form>