<?php
/**
 * Magento Developer's Toolbar
 *
 * @category    Ash
 * @package     Ash_Bar
 * @copyright   Copyright (c) 2012 August Ash, Inc. (http://www.augustash.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<table id="ashbar-block-table" class="table table-striped">
    <thead>
        <tr>
            <th><?php echo $this->__('Block Name'); ?></th>
            <th><?php echo $this->__('Template File'); ?></th>
            <th><?php echo $this->__('Times Instantiated'); ?></th>
        </tr>
    </thead>
    <tbody id="ashbar-block-table-body">
    </tbody>
</table>
