<?php
/**
 * Magento Developer's Toolbar
 *
 * @category    Ash
 * @package     Ash_Bar
 * @copyright   Copyright (c) 2012 August Ash, Inc. (http://www.augustash.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="alert alert-info">
    <strong>Note:</strong> This table captures collections which inherit from core
    Magento collection class <code>Mage_Core_Model_Resource_Db_Collection_Abstract</code>.
    Legacy collections which inherit directly from <code>Varien_Data_Collection_Db</code>
    are not captured.
</div>

<table id="ashbar-collection-table" class="table table-striped">
    <thead>
        <tr>
            <th><?php echo $this->__('Collection Name'); ?></th>
            <th><?php echo $this->__('Times Instantiated'); ?></th>
        </tr>
    </thead>
    <tbody id="ashbar-collection-table-body">
    </tbody>
</table>
