<?php
/**
 * Magento Developer's Toolbar
 *
 * @category    Ash
 * @package     Ash_Bar
 * @copyright   Copyright (c) 2012 August Ash, Inc. (http://www.augustash.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if ($this->getTimers()): ?>

<table id="ashbar-profiler-table" class="table table-striped">
    <thead>
        <tr>
            <th><?php echo $this->__('Name'); ?></th>
            <th><?php echo $this->__('Time'); ?></th>
            <th><?php echo $this->__('Count'); ?></th>
            <th><?php echo $this->__('Count'); ?></th>
            <th><?php echo $this->__('Real Memory'); ?></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($this->getTimers() as $_name => $_data): ?>

        <tr>
            <td><?php echo $_name; ?></td>
            <td><?php echo Mage::helper('ash_bar')->formatNumber($_data['sum']); ?></td>
            <td><?php echo $_data['count']; ?></td>
            <td><?php echo Mage::helper('ash_bar')->formatNumber($_data['emalloc'], 0); ?></td>
            <td><?php echo Mage::helper('ash_bar')->formatBytes($_data['realmem']); ?></td>
        </tr>

    <?php endforeach; ?>
    </tbody>
</table>

<?php else: ?>

<div class="alert alert-info">
    <!-- <button type="button" class="close" data-dismiss="alert">×</button> -->
    <strong>Heads up!</strong> The code profiler is disabled and cannot return results.
</div>

<?php endif;?>
