<?php
/**
 * Magento Developer's Toolbar
 *
 * @category    Ash
 * @package     Ash_Bar
 * @copyright   Copyright (c) 2012 August Ash, Inc. (http://www.augustash.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div id="ashbar-system-results">
</div>

<div class="btn-group">
    <?php if (Mage::helper('ash_bar/cache')->isEnabled()): ?>
    <button id="ashbar-clean-cache" class="btn btn-small btn-info">
        <?php echo $this->__('Clean Cache'); ?>
    </button>
    <button id="ashbar-toggle-cache" class="btn btn-small btn-danger">
        <?php echo $this->__('Disable'); ?>
    </button>

    <?php else: ?>

    <button id="ashbar-toggle-cache" class="btn btn-small">
        <?php echo $this->__('Enable Cache'); ?>
    </button>
    <?php endif; ?>
</div>

<div class="btn-group">
    <?php if (Mage::getStoreConfigFlag('dev/log/active')): ?>
    <button id="ashbar-toggle-logs" class="btn btn-small btn-danger">
        <?php echo $this->__('Disable Logging'); ?>
    </button>

    <?php else: ?>

    <button id="ashbar-toggle-logs" class="btn btn-small">
        <?php echo $this->__('Enable Logging'); ?>
    </button>
    <?php endif; ?>
</div>

<div class="btn-group">
    <?php if (Mage::getStoreConfigFlag('dev/debug/template_hints')): ?>

    <button id="ashbar-toggle-hints" class="btn btn-small btn-danger">
        <?php echo $this->__('Disable Template Hints'); ?>
    </button>

    <?php else: ?>

    <button id="ashbar-toggle-hints" class="btn btn-small">
        <?php echo $this->__('Enable Template Hints'); ?>
    </button>
    <?php endif; ?>
</div>
