<?php
$customerId = 0;
if (Mage::getSingleton('customer/session')->isLoggedIn()) {
	$customerId = Mage::getSingleton('customer/session')->getCustomerId();
}
?>

<?php $_code = $this->getMethodCode(); ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">

    <!-- Display Saved Credit Cards for Selection -->
    <?php 
    $quote = Mage::getSingleton('checkout/session')->getQuote();
    $cartItems = $quote->getAllVisibleItems();
    $subscription = 0;
    foreach ($cartItems as $item){
		if($item->getData('product_type')=='subscription_virtual'){
			$subscription = 1;
			break;
		}
    }
    $savedCreditCards = $this->getSavedCreditCards($customerId); 
    if (!empty($savedCreditCards) && $customerId != 0 && $subscription!=1): 
    ?>
    <!--  This is for the saved cc on file -->
    <li id="<?php echo $_code ?>_cc_saved">
        <ul class="inner-form">
            <li class="form-alt"><label class="required"><em>*</em><?php echo $this->__('Use Saved Credit Card') ?></label></li>
            <?php foreach($savedCreditCards as $ccSaved): ?>
            <?php $display = "Use card on file with last 4 digits:".$ccSaved['last4'] ?>
            <li>
            	<input type="radio" name="payment[ccsave_id]" id="<?php echo $ccSaved['id'] ?>" class="" onClick="<?php echo $_code ?>useSavedCC(this.value);" value="<?php echo $ccSaved['id'] ?>"> <?php echo $this->__($display) ?>
				<input type=hidden id="<?php echo 'cctype'.$ccSaved['id'] ?>" name="<?php echo 'cctype'.$ccSaved['id'] ?>" value="<?php echo $ccSaved['type'] ?>">
				<input type=hidden id="<?php echo 'fullcc'.$ccSaved['id'] ?>" name="<?php echo 'fullcc'.$ccSaved['id'] ?>" value="<?php echo $ccSaved['fullcc'] ?>">
				<input type=hidden id="<?php echo 'expmonth'.$ccSaved['id'] ?>" name="<?php echo 'expmonth'.$ccSaved['id'] ?>" value="<?php echo $ccSaved['expmonth'] ?>">
				<input type=hidden id="<?php echo 'expyear'.$ccSaved['id'] ?>" name="<?php echo 'expyear'.$ccSaved['id'] ?>" value="<?php echo $ccSaved['expyear'] ?>">
            </li>
            <?php endforeach ?>
            <li class="adv-container">&nbsp;</li>
        </ul>
    </li>
	<?php endif; ?>
	<!--  This is for a new credit card -->
	<li class="form-alt">
		<input style="float: left;" type="radio" name="" id="<?php echo $_code ?>_cc_new" class="" onClick="<?php echo $_code ?>useNewCC();" value="" <?php if (empty($savedCreditCards)): echo ' CHECKED'; endif; ?> />
		<label class="required"><em>*</em>&nbsp;&nbsp;<?php echo $this->__('Enter New Credit Card') ?></label>
	</li>
	<li id="<?php echo $_code ?>_cc_entered" style="display:block;">
	<ul class="inner-form">
    <li>
        <label for="<?php echo $_code ?>_cc_type" class="required"><em>*</em><?php echo $this->__('Credit Card Type') ?></label>
        <div class="input-box">
            <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" class="required-entry validate-cc-type-select">
                <option value=""><?php echo $this->__('--Please Select--')?></option>
            <?php $_ccType = $this->getInfoData('cc_type') ?>
            <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                <option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
            <?php endforeach ?>
            </select>
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-cc-number validate-cc-type" value="" />
        </div>
    </li>
    <li id="<?php echo $_code ?>_cc_type_exp_div">
        <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="month validate-cc-exp required-entry">
                <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
            </div>
            <div class="v-fix">
                <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year required-entry">
                <?php foreach ($this->getCcYears() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
            </div>
        </div>
    </li>
    <?php echo $this->getChildHtml() ?>
    <?php if($this->hasVerification()): ?>
    <li id="<?php echo $_code ?>_cc_type_cvv_div">
        <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" />
            </div>
            <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this???') ?></a>
        </div>
    </li>
    <?php endif; ?>
    </ul>
    </li>
    

</ul>
<script type="text/javascript">
        function <?php echo $_code ?>useSavedCC(ccSavedId) {     	

        	document.getElementById('authorizenetcim_cc_new').checked = false;
                   
            var t = document.getElementById('<?php echo $_code ?>_cc_type');
				t.setAttribute("class","");
				t.value = document.getElementById('cctype'+ccSavedId).value;
            
        	var cc = document.getElementById('<?php echo $_code ?>_cc_number');
				cc.setAttribute("class","");
				cc1 = document.getElementById('fullcc'+ccSavedId).value;
				cc.value = parseInt(cc1,10);

			var em = document.getElementById('<?php echo $_code ?>_expiration');
				em.setAttribute("class","");
				em.value= document.getElementById('expmonth'+ccSavedId).value;

			var ey= document.getElementById('<?php echo $_code ?>_expiration_yr');
				ey.setAttribute("class","");
				ey.value= document.getElementById('expyear'+ccSavedId).value;

			var cvn = document.getElementById('<?php echo $_code ?>_cc_cid');
				cvn.setAttribute("class","");

				if (t.value=='AE')
				{
					cvn.value='1111';
				}
				else
				{
					cvn.value='111';
				}

			var rb = document.getElementById('<?php echo $_code ?>_cc_new');
				rb.checked=false;
				rb.setAttribute("class","");				

			var li = document.getElementById('<?php echo $_code ?>_cc_entered');
				li.style.display = 'none';		
        };

        function <?php echo $_code ?>useNewCC() {

			// This will uncheck the saved cc
			var payments = document.getElementsByName('payment[ccsave_id]');

			for(var i = 0; i < payments.length; i++){
				var element = payments[i].getAttribute('id');
				document.getElementById(element).checked = false;
			}
            
            var t = document.getElementById('<?php echo $_code ?>_cc_type');
				t.setAttribute("class","required-entry validate-cc-type-select");
				t.value='';	
				
        	var cc = document.getElementById('<?php echo $_code ?>_cc_number');
				cc.setAttribute("class","input-text validate-cc-number");
				cc.value='';	

			var em = document.getElementById('<?php echo $_code ?>_expiration');
				em.setAttribute("class","month validate-cc-exp required-entry");
				em.value='';	

			var ey= document.getElementById('<?php echo $_code ?>_expiration_yr');
				ey.setAttribute("class","year required-entry");
				ey.value='';

			var cvn = document.getElementById('<?php echo $_code ?>_cc_cid');
				cvn.setAttribute("class","required-entry input-text validate-cc-cvn");
				cvn.value='';

			var rb = document.getElementsByName('payment[ccsave_id]');
				for(var i=0;i<rb.length;i++)
			    	rb[i].checked = false;
				//rb.checked=false;
				//rb.setAttribute("class","");

			var li = document.getElementById('<?php echo $_code ?>_cc_entered');
				li.style.display = 'block';
			
        };     
</script>