<?php
/**
 * Ash Slideshow Extension
 *
 * @category  Ash
 * @package   Ash_Slideshow
 * @copyright Copyright (c) 2014 August Ash, Inc. (http://www.augustash.com)
 * @license   http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @author    August Ash Team <core@augustash.com>
 */


/**
 * DEFAULT LAYOUT
 *
 * Standard slide show functionality
 */
?>

<div class='row'>
    <div class="ash-slideshow-wrapper <?php echo $config['layout']; ?>  small-12 columns">
        <ul id="ash_slideshow-<?php echo $config['id'];?>" class="bxslider no-bullet">
            <?php foreach($slides as $slide): ?>
                <li class='slide'>
                    <img src="<?php echo Mage::helper('ash_slideshow')->getAssetUrl($slide); ?>" alt="<?php echo $slide->getData('title'); ?>" title="<?php echo $slide->getData('title'); ?>" />
                </li>
            <?php endforeach; ?>
        </ul>
        <script type="text/javascript">
            //<![CDATA[
                jQuery(document).ready(function(){
                    var slider      = "ash_slideshow-<?php echo $config['id'];?>";
                    var bxOptions   = <?php echo $bxConfig; ?>;
                    jQuery("#" + slider).bxSlider(bxOptions);
                });
            //]]>
        </script>
    </div>
</div>
