<?php
/**
 * Ash Slideshow Extension
 *
 * @category  Ash
 * @package   Ash_Slideshow
 * @copyright Copyright (c) 2014 August Ash, Inc. (http://www.augustash.com)
 * @license   http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @author    August Ash Team <core@augustash.com>
 */


/**
 * HERO LAYOUT
 *
 * Slides will have:
 *
 *  + Large background image/video
 *  + Large H1/H2 title
 *  + Description paragraph(s)
 *  + Call to Action button
 */
?>

<div class='row'>
    <div class="ash-slideshow-wrapper <?php echo $config['layout']; ?> small-12 columns">
        <ul id="ash_slideshow-<?php echo $config['id'];?>" class="bxslider no-bullet">
            <?php foreach($slides as $slide): ?>
                <li class='slide'>
                    <div class='slide-bg'>
                        <img src="<?php echo Mage::helper('ash_slideshow')->getAssetUrl($slide); ?>" alt="<?php echo $slide->getData('title'); ?>" title="<?php echo $slide->getData('title'); ?>" />
                    </div>

                    <div class='promo-details'>
                        <hgroup>
                            <h1 class='slide-title '><?php echo $slide->getData('title'); ?></h1>
                            <?php if($slide->getData('subtitle')): ?>
                                <h2 class='slide-title subheader'><?php echo $slide->getData('subtitle'); ?></h2>
                            <?php endif; ?>
                        </hgroup>
                        <p class='slide-desc'><?php echo $slide->getData('description'); ?></p>
                        <div class='slide-call-to-action'>
                            <a class='button radius' href="<?php echo $slide->getData('link_url'); ?>">
                                <?php echo $slide->getData('link_text'); ?>
                            </a>
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
        </ul>
        <script type="text/javascript">
            //<![CDATA[
                jQuery(document).ready(function(){
                    var slider      = "ash_slideshow-<?php echo $config['id'];?>";
                    var bxOptions   = <?php echo $bxConfig; ?>;
                    jQuery("#" + slider).bxSlider(bxOptions);
                });
            //]]>
        </script>
    </div>
</div>
