<?php
/**
 * Ash Slideshow Extension
 *
 * @category  Ash
 * @package   Ash_Slideshow
 * @copyright Copyright (c) 2014 August Ash, Inc. (http://www.augustash.com)
 * @license   http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @author    August Ash Team <core@augustash.com>
 */


/**
 * PRODUCT SLIDER LAYOUT
 *
 * Slides will have:
 *
 *  + Large background image/video that will be a link
 *  + One title that will be a link displayed underneath image
 *  + Description paragraph(s) that will display underneath image
 */
?>

<div class='row'>
    <div class="ash-slideshow-wrapper <?php echo $config['layout']; ?>  small-12 columns">
        <ul id="ash_slideshow-<?php echo $config['id'];?>" class="bxslider no-bullet">
            <?php foreach($slides as $slide): ?>
                <li class='slide'>
                    <?php if($slide->getData('link_url')): ?>
                        <a href="<?php echo $slide->getData('link_url'); ?>">
                            <img src="<?php echo Mage::helper('ash_slideshow')->getAssetUrl($slide); ?>" alt="<?php echo $slide->getData('title'); ?>" title="<?php echo $slide->getData('title'); ?>" />
                        </a>
                    <?php else: ?>
                        <img src="<?php echo Mage::helper('ash_slideshow')->getAssetUrl($slide); ?>" alt="<?php echo $slide->getData('title'); ?>" title="<?php echo $slide->getData('title'); ?>" />
                    <?php endif; ?>

                    <div class='promo-details'>
                        <a href="<?php echo $slide->getData('link_url'); ?>">
                            <h3 class='slide-title '><?php echo $slide->getData('title'); ?></h3>
                        </a>
                        <p class='slide-desc'><?php echo $slide->getData('description'); ?></p>
                    </div>
                </li>
            <?php endforeach; ?>
        </ul>
        <script type="text/javascript">
            //<![CDATA[
                jQuery(document).ready(function(){
                    var slider      = "ash_slideshow-<?php echo $config['id'];?>";
                    var bxOptions   = <?php echo $bxConfig; ?>;
                    jQuery("#" + slider).bxSlider(bxOptions);
                });
            //]]>
        </script>
    </div>
</div>
