<?php $_source  = $this->getSource() ?>
<?php $this->setPriceDataObject($_source) ?>

<?php if ((float) $_source->getSnapCardsAmount()): ?>
    <?php $_snapCards = Mage::helper('snap_card')->getCards($_source); ?>
    <?php foreach ($_snapCards as $_card): ?>
        <?php $_baseAmount = $_card['ba']; ?>
        <?php $_amount = $_card['a']; ?>
        <?php $_code = $_card['c']; ?>

        <tr>
            <td class="label"><?php echo Mage::helper('snap_card')->__('Gift Card (%s)', $_code) ?></td>
            <td>
                <?php echo $this->displayPrices(-$_baseAmount, -$_amount); ?>
            </td>
        </tr>
    <?php endforeach; ?>
<?php endif; ?>
