<?php /** @var $this Smartbear_Alertsite_Block_Adminhtml_Create */ ?>
<div class="main-col-inner">
    <div id="messages">

    </div>

    <div class="content-header">
        <table cellspacing="0">
            <tbody>
                <tr>
                    <td>
                        <h3>AlertSite - Account Recovery/Edit</h3>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>


    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend">New AlertSite Account Information</h4>
        </div>
        <div class="fieldset">
            <?php echo $this->getChildHtml('alertsite.subheader'); ?>
            <form action="<?php echo $this->getFormAction(); ?>" method="post" id="alertsite-provision" >
                <table class="form-list">
                    <input name="form_key" type="hidden" value="<?php echo $this->getFormKey(); ?>">
                    <tr>
                        <td class="label">
                            <label for="login_email" style="">Login Email <span class="required">*</span><br /><em>(Email is Case Sensitive)</em></label>
                        </td>
                        <td class="value">
                            <input id="login_email" autocomplete="off" class="validate-email input-text" name="login_email" value="<?php echo $this->getUsername(); ?>" type="text">
                        </td>
                    </tr>
                    <tr>
                        <td class="label">
                            <label for="password" style="">Account Password <span class="required">*</span> <br /><em>(Password is case sensitive)</em></label>
                        </td>
                        <td class="value">
                            <input id="password" autocomplete="off" name="password" class="input-text" type="password" value="<?php echo $this->getPassword(); ?>">
                        </td>
                    </tr>
                    <tr>
                        <td class="label">
                            <label for="basic_site_id" style="">Basic Site ID <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <input id="basic_site_id" autocomplete="off" name="basic_site_id" class="input-text" value="<?php echo $this->getSiteDeviceId(); ?>" type="text">
                        </td>
                    </tr>
                    <tr>
                        <td class="label">
                            <label for="deja_url_id" style="">Deja URL ID <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <input id="deja_url_id" autocomplete="off" name="deja_url_id" class="input-text" type="text" value="<?php echo $this->getDejaclickDeviceId(); ?>">
                        </td>
                    </tr>


                    <tr>
                        <td colspan="2"><br /></td>
                    </tr>

                    <tr>
                        <td>
                            <br />
                            <button type="submit" class="button"><span>Save AlertSite Account</span>&nbsp;<img style="position:relative; top:3px;" class="smartbear-icon" src="<?php echo $this->getSkinUrl($this->__('smartbear/alertsite/images/alertsite_15_icon.png')); ?>" alt="AlertSite" /></button>
                        </td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
</div>