<?php

/**
 * Core module for providing common functionality between BraceletBuilder and other related submodules
 *
 * @category    Pan
 * @package     Pan_JewelryDesigner
 * @copyright   Copyright (c) 2014 August Ash, Inc. (http://www.augustash.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

// instantiate helper
$_helper            = Mage::helper('pan_jewelrydesigner');
$inAdminArea        = $_helper->inAdminArea();
$customerLoggedIn   = $_helper->isCustomerLoggedIn();
$cssClass           = '';
$cssClass           .= ($inAdminArea) ? 'admin logged-in' : 'frontend';

if (!$inAdminArea) {
    $cssClass .= ($customerLoggedIn) ? ' logged-in' : ' guest';
}

if($inAdminArea){
    $dataAttr = ' data-admin-id="' . $_helper->getAdminUser()->getId() . '"';

    $formKey = Mage::getSingleton('core/session')->getFormKey();
    $dataAttr .= ' data-form-key="' . $formKey . '"';

    $secretKey = Mage::getSingleton('adminhtml/url')->getSecretKey();
    $dataAttr .= ' data-secret-key="' . $secretKey . '"';
} else {
    $dataAttr = '';
}

?>

<!--[if lt IE 9]>
<div class='browser-warning'>
    <p>Your browser is too old to support the necessary requirements for the Build a Bracelet! <a href="http://browsehappy.com/">Upgrade to a different browser</a> to experience the Build a Bracelet feature.</p>
</div>
<script type='text/javascript'>
//<![CDATA[
    jQuery(document).ready(function(){
        jQuery('.designer_app_wrapper').addClass('hidden');
    });
//]]>
</script>
<![endif]-->


<div class="designer_app_wrapper <?php echo $cssClass; ?>"<?php echo $dataAttr; ?>>
    <div class="mobile_message">
        <p>To utilize the Build a Bracelet application you must use a device with a higher resolution.</p>
    </div>

    <div class='loader'>
        <span class='loader-icon'></span>
        <p>Loading...</p>
    </div>
    <!-- Angular.JS app -->
    <div id="ng-app" data-ng-app="jewelryDesigner" ng-app="jewelryDesigner" class='designer_app'>
        <div ui-view></div>
    </div>
</div>
