<?php

/**
 * Core module for providing common functionality between BraceletBuilder and other related submodules
 *
 * @category    Pan
 * @package     Pan_JewelryDesigner
 * @copyright   Copyright (c) 2014 August Ash, Inc. (http://www.augustash.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

// instantiate helper
$_helper = Mage::helper('pan_jewelrydesigner');
?>

<h1>The Jewelry Designer is not enabled!</h1>

<p>You can enable it from <strong>System->Configuration->Pandora Extensions->Jewelry Designer</strong> configuration settings.</p>
