<?php
/**
 * Magento Developer's Toolbar
 *
 * @category    Ash
 * @package     Ash_Bar
 * @copyright   Copyright (c) 2012 August Ash, Inc. (http://www.augustash.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<link type="text/css" href="<?php echo $this->getSkinPath(); ?>/css/ash-toolbar.css" rel="stylesheet" />
<link type="text/css" href="<?php echo $this->getSkinPath(); ?>/css/bootstrap.min.css" rel="stylesheet" />
<link type="text/css" href="<?php echo $this->getSkinPath(); ?>/css/font-awesome.css" rel="stylesheet" />
<script type="text/javascript" src="<?php echo $this->getSkinPath(); ?>/js/bootstrap.min.js"></script>
<script type="text/javascript" src="<?php echo $this->getSkinPath(); ?>/js/jquery.cookie.js"></script>
<script type="text/javascript" src="<?php echo $this->getSkinPath(); ?>/js/ash-toolbar.js"></script>
