<?php
/**
 * Magento Developer's Toolbar
 *
 * @category    Ash
 * @package     Ash_Devbar
 * @copyright   Copyright (c) 2014 August Ash, Inc. (http://www.augustash.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if (Mage::helper('ash_devbar')->isEnabled()): ?>
<?php if (Mage::helper('ash_devbar')->useIncludedZurb()): ?>
<script type="text/javascript" src="<?php echo $this->getAssetBaseUrl(); ?>js/foundation.min.js"></script>
<?php endif; ?>
<script type="text/javascript" src="<?php echo $this->getAssetBaseUrl(); ?>js/jquery.cookie.js"></script>
<script type="text/javascript" src="<?php echo $this->getAssetBaseUrl(); ?>js/toolbar.js"></script>
<script type="text/javascript">
//<![CDATA[
jQuery(document).ready(function(){
    var tabs = <?php echo $this->getTabsAsJson(); ?>;
    var menu = [];

    menu.push('<div id="devbar-activator" class="fixed">');
        menu.push('<img class="devbar-logo" src="<?php echo $this->getAssetBaseUrl(); ?>img/mage_logo.gif" alt="<?php echo $this->__('Toggle Toolbar') ?>" />');
    menu.push('</div>');
    menu.push('<div class="devbar">');
        menu.push('<div id="devbar-menu" class="fixed" style="display:none;">');
            menu.push('<nav class="top-bar" data-topbar data-options="is_hover: false">');
                menu.push('<section class="top-bar-section">');
                    menu.push('<ul class="left">');

                    // add menu items from rendered tab blocks
                    jQuery.each(tabs, function buildMenuItem(key, tab){
                        if (tab.css.length > 0) {
                            var css = ' class="' + tab.css.join(' ') + '"';
                        } else {
                            var css = '';
                        }
                        menu.push('<li' + css + '>' + tab.label + '</li>');
                    });

                    menu.push('</ul>');
                menu.push('</section>');
            menu.push('</nav>');

            // add menu items from rendered tab blocks
            jQuery.each(tabs, function buildItemContent(key, tab){
                if (tab.html) {
                    menu.push('<section id="devbar-'+ tab.id +'-content" class="devbar-tab-section fixed" style="display:none;">');
                    menu.push(tab.html);
                    menu.push('</section>');
                }
            });
        menu.push('</div>');
    menu.push('</div>');
    jQuery('body').prepend(menu.join(''));

    // initialize the toolbar
    jQuery('#devbar-menu').devbar(collectedJsonData);
});
//]]>
</script>
<?php endif; ?>
