<?php
/**
 * Magento Developer's Toolbar
 *
 * @category    Ash
 * @package     Ash_Devbar
 * @copyright   Copyright (c) 2014 August Ash, Inc. (http://www.augustash.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if (Mage::helper('ash_devbar')->isEnabled()): ?>
<?php if (Mage::helper('ash_devbar')->useIncludedZurb()): ?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getAssetBaseUrl(); ?>css/foundation.min.css" media="all" />
<?php endif; ?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getAssetBaseUrl(); ?>css/toolbar.css" media="all" />
<?php endif; ?>
