<?php
/**
 * Add Jquery/Jquery UI support
 *
 * @category    Ash
 * @package     Ash_Jquery
 * @copyright   Copyright (c) 2013 August Ash, Inc. (http://www.augustash.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

// instantiate helper
$_helper = Mage::helper('ash_jquery');

// figure out which library version to include
if ($_helper->useCdn()) {
    if ($_helper->useMinified()) {
        $jqueryName   = $_helper->getJqueryVersion() . '/jquery.min.js';
        $migrateName  = '/jquery-migrate-'. $_helper->getJqueryMigrateVersion() . '.min.js';
        $jqueryUiName = $_helper->getJqueryUiVersion() . '/jquery-ui.min.js';
    } else {
        $jqueryName   = $_helper->getJqueryVersion() . '/jquery.js';
        $migrateName  = '/jquery-migrate-'. $_helper->getJqueryMigrateVersion() . '.js';
        $jqueryUiName = $_helper->getJqueryUiVersion() . '/jquery-ui.js';
    }
}
?>
<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
<title><?php echo $this->getTitle() ?></title>
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<!--[if lt IE 7]>
<script type="text/javascript">
//<![CDATA[
    var BLANK_URL = '<?php echo $this->helper('core/js')->getJsUrl('blank.html') ?>';
    var BLANK_IMG = '<?php echo $this->helper('core/js')->getJsUrl('spacer.gif') ?>';
//]]>
</script>
<![endif]-->

<?php if ($_helper->useCdn()) : ?>
<!-- JQUERY CDN -->
<?php if ($_helper->isJqueryEnabled('cdn')) : ?>
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/<?php echo $jqueryName; ?>"></script>
<script type="text/javascript">jQuery.noConflict();</script>
<?php if ($_helper->isJqueryMigrateEnabled('cdn')) : ?>
<script type="text/javascript" src="//code.jquery.com/<?php echo $migrateName; ?>"></script>
<?php endif; ?>
<?php endif; ?>
<?php if ($_helper->isJqueryUiEnabled('cdn')) : ?>
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jqueryui/<?php echo $jqueryUiName; ?>"></script>
<?php endif; ?>
<!-- /JQUERY CDN -->
<?php endif; ?>

<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>
<?php echo $this->helper('core/js')->getTranslatorScript() ?>
<?php echo $this->getIncludes() ?>
