<?php $_source  = $this->getSource() ?>
<?php $this->setPriceDataObject($_source) ?>

<?php if ((float) $_source->getSnapCardsAmount()): ?>
    <tr>
        <td class="label">
            <?php echo Mage::helper('snap_card')->__('Gift Cards') ?>
        </td>
        <td>
            <?php echo $this->displayPrices(-$_source->getBaseSnapCardsAmount(), -$_source->getSnapCardsAmount()); ?>
        </td>
    </tr>
<?php endif; ?>
