<?php

/**
 * RocketWeb
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   RocketWeb
 * @package    default_default
 * @copyright  Copyright (c) 2012 RocketWeb (http://rocketweb.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     RocketWeb
 */

?>
<?php
/**
 * @see RocketWeb_GoogleBaseFeedGenerator_Block_Adminhtml_System_Config_Updatebtn
 */
?>
<?php echo $this->__('Enter SKU to test a single product, or use an offset and a limit to generate a set of products.'); ?>
<table>
    <tr>
        <td>
            <div style="padding-bottom:5px;">
                <label style="padding-right:11px;"
                       for="<?php echo $this->getHtmlId() ?>sku"><?php echo $this->__('Sku / ID') ?>:</label>&nbsp;
                <input style="width:150px;" class="input-text" type="text" value=""
                       id="<?php echo $this->getHtmlId() ?>sku"/>
            </div>
            <div style="padding-bottom:5px;">
                <label for="<?php echo $this->getHtmlId() ?>sku"><?php echo $this->__('Or offset') ?>:</label>&nbsp;
                <input style="width:35px;" class="input-text" type="text" value=""
                       id="<?php echo $this->getHtmlId() ?>offset"/>
                <label style="padding-left:10px;"
                       for="<?php echo $this->getHtmlId() ?>sku"><?php echo $this->__('limit') ?>:</label>&nbsp;
                <input style="width:35px;" class="input-text" type="text" value=""
                       id="<?php echo $this->getHtmlId() ?>limit"/>
            </div>

            <button class="scalable" type="button" id="<?php echo $this->getHtmlId() ?>">
                <span><?php echo $this->escapeHtml($this->getButtonLabel()); ?></span>
            </button>
        </td>
    </tr>
</table>
<script type="text/javascript">
    //<![CDATA[
    $('<?php echo $this->getHtmlId() ?>').observe('click', function (e) {
        <?php if (!$this->isButtonAllowed()):?>
        alert("<?php echo $this->__('Feed generation not allowed in global scope or website scope. Please change to store view scope.') ?>");
        Event.stop(e);
        return;
        <?php endif;?>
        var url = "<?php echo $this->getButtonUrl()?>";
        var sku = $('<?php echo $this->getHtmlId() ?>sku').value;
        var offset = $('<?php echo $this->getHtmlId() ?>offset').value;
        var limit = $('<?php echo $this->getHtmlId() ?>limit').value;
        url += "?testmode=1";
        if (sku != "") {
            url += "&sku=" + sku + "";
        }
        else if (offset != "" && limit != "") {
            if (limit <= 100) {
                url += "&offset=" + offset + "&" + "limit=" + limit + "";
            }
            else {
                alert("Limit too high. Must be less than 100.");
                Event.stop(e);
                return;
            }
        }
        else {
            alert("Enter Sku or Limit and Offset.");
            Event.stop(e);
            return;
        }

        url += "&uniqueid=" + "<?php echo urlencode(uniqid(rand(), true))?>";

        popWin(url, 'generategbasefeed_test', 'toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=no, left=200, top=100, width=1000, height=900');
        Event.stop(e);
    })
    //]]>
</script>